---
title: "Market_Access_BOL"
author: "Evelyn Sanchez"
date: "2/25/2020"
output: html_document
---
```{r setup, include=FALSE}
require("knitr")
# Define the working directory for the entire markdown file to enable relative path
knitr::opts_knit$set(root.dir = "/Users/eves/Dropbox/LATAM_WorldBank/")
```
#Load libraries
```{r}
#clean environment
rm(list=ls())

library(BAMMtools)
library(classInt)
library(data.table)
library(doBy)
library(dplyr)
library(foreign)
library(ggplot2)
library(mapproj)
library(maptools)
library(raster)
library(rgeos)
library(RColorBrewer)
library(rgdal)
library(shapefiles)
library(sp)
library(stringr)
library(tidyverse)
library(viridis)
library(viridisLite)
library (BBmisc)
```

#Create directories
```{r}
dir_shp <- "./Boundaries/BOL/"                     #Confirm path
dir_cap <- "./Boundaries/Capitals/"                #Confirm path
dir_raw <- "./Data/Market Access/BOL/"            #Confirm path
dir_out <- "./Index/BOL/Output/"                  #Confirm path
dir_map <- "./Index/BOL/Maps/"                  #Confirm path
getwd()

#Modify raster name and shapefile

rdata = paste(dir_raw, "market_access_d6_BOL.tif", sep = "")
inshp="Bolivia" 
```

#Reporject market access raster 
```{r}
#Raster from Market Access is in different UTM projection, needs to be reprojected to match the shapefile (WGS84)
myraster <- raster(rdata)

#Set desire projection
sr <- "+proj=longlat +datum=WGS84 +no_defs" 

#Reproject raster 
myraster <- projectRaster(myraster, crs = sr)
writeRaster(myraster, filename=paste0(dir_out, "Reproj_Raster_BOL.tif"), overwrite=TRUE)
```

#Open country shapefile
```{r}
country_shp <- readOGR(dsn = dir_shp, layer=inshp) %>% 
spTransform(crs("+proj=longlat +datum=WGS84 +no_defs"))
```
#Crop raster
```{r}
#Mark -999 as NA value
NAvalue(myraster) <- -999
# Clipp 
country_raster <- crop(myraster, country_shp)
#Mask raster for maps
country_raster_msk <-mask(myraster, country_shp) 

```

#Extract raster values 
```{r}
#Extract raster values function
desc_stats_fun <- function(clipped, shp){   
  # Creates dataframes with descriptive stats per unit of analysis.
  # Inputs: 
    # clipped: clipped raster in R format
    # shp: shapefile with polygons of interest
    # shp_id_num: number of variable in shapefile with id
    # Return: summary of df
  
    # Estimate basic stats per rayon
    stats = data.frame(raster::extract(x=clipped, y = shp, df=TRUE))
    colnames(stats)[1] = "id"
    colnames(stats)[2] = "value"
    
    desc_stats <- stats %>%
    group_by(id) %>% 
    dplyr::summarise(mean=mean(value, na.rm=TRUE),  max=max(value, na.rm=TRUE), min=min(value, na.rm=TRUE), median=median(value, na.rm=TRUE), std=sd(value, na.rm=TRUE), obs=n(), p90=quantile(value, probs=0.90, na.rm=TRUE), p95=quantile(value, probs=0.95, na.rm=TRUE))
    
    desc_stats$cv <- desc_stats$std / desc_stats$mean
    
    return(desc_stats)}


#Execute extracting function
mark_stats<- desc_stats_fun(country_raster, country_shp)

```

#Merge values with districts names 
```{r}
# Extract names
country_shp@data
dis_names <- country_shp@data

#Create an "id" column to merge values with names
dis_names <- tibble::rowid_to_column(dis_names, "id")
dis_names$id <- as.numeric(as.character(dis_names$id))

dis_names <-dis_names%>%
  dplyr::select(id, TARGET_FID, NAME_0, NAME_1)


#Stablish same key and merge 
mark_stats$id <- as.numeric(mark_stats$id)
mark_stats <- mark_stats %>% left_join(dis_names, by="id")

colnames(mark_stats)

#Clean dataframe
mark_stats<-mark_stats%>%
dplyr::select(TARGET_FID, NAME_0, NAME_1, median, mean, max, std, obs, p90, p95, cv)

#Save all stats
write.csv(mark_stats, file= paste(dir_out, "MKT_Access_BOL_Stats.csv", sep = ""))  #Change name of file
```

#Map raster
```{r}
#Convert raster to dataframe 
ras_df <- as.data.frame(country_raster_msk, xy=TRUE, na.rm=TRUE)
colnames(ras_df) <- c("x", "y", "value")

#Fortify shapefile for mapping 
shape_fort <- fortify(country_shp, region="TARGET_FID") %>%
  mutate(id=as.numeric(id))

#Include capitals 
#Load capitals file

#Capitals Names, shapefile
capitals <- readOGR(dsn = dir_cap, layer = "Capitals") %>%          #Change filename
  spTransform(crs("+proj=longlat +datum=WGS84 +no_defs"))

capitals_points <-capitals@data%>%
  dplyr::select("NAME", "UN_FID", "UN_LAT", "UN_LONG", "ADM0_A3")

capital_filter <- capitals_points[capitals_points$ADM0_A3 == "BOL",]
capital_filter$UN_LAT<-  -16.50
capital_filter$UN_LONG<- -68.1333
```

#Map
```{r}
#Establish map theme
theme_map <- function(...) {
  theme_classic() +
    theme(
      text = element_text(color = "#22211d"),
      axis.line = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5),
      plot.caption = element_text(hjust = 0.5),
      ...
    )
}


#Create map

fig <- ggplot() +
  geom_raster(data=ras_df, aes(x=x,y=y, fill=value), alpha=1) +
  # rayon polygons with data
  geom_polygon(data=shape_fort, aes(x=long, y=lat, group=group), 
               fill=NA, color="grey60", size=0.25) +
  geom_point(data=capital_filter, aes(x=UN_LONG, 
                                         y=UN_LAT), color="black", size= 1, pch = 16)+
    geom_text(data = capital_filter, aes(UN_LONG, UN_LAT, label = NAME), size = 3, hjust= .29 ,vjust=-1.5, fontface=2)+
  
  # for projection
  coord_equal() +
  
  # add the previously defined basic theme + color
  theme_map() +
    
  # labels
   labs( x = NULL, 
         y = NULL, 
         title = "Markets Access", 
         subtitle = "Source: World Bank", 
         caption = "Note: Proxy of market accessibility based on the travel time to \n nearest markets (main cities), weighted by the population.") +
  # legend
  theme(legend.title = element_text(size = 10)) +
  scale_fill_viridis(
    option = "magma",
    direction = -1,
    name = "Market Access",
    labels=c("Min","", "Medium", "", "Max")
)

fig

#Save map
ggsave(paste(dir_map,"Raster_Market_raw.png", sep=""), height=6, width = 8, units = c("in"))

```



