---
title: "Benchmarking_Graphs"
author: "Evelyn Sanchez"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/eves/Dropbox/MENA/")
```

```{r}
library(WDI)
#library(plyr)
library(dplyr)
library(readxl)
library(rvest)
library(tidyverse)
library(data.table)
library(ggplot2)
library(grid)
library(Hmisc)
```

#Set Directories
```{r}
dir_raw<-"./Data/Benchmarking/SD_Profiles/Raw indicators/"
dir_int<- "./Data/Benchmarking/SD_Profiles/Integrated data/"
dir_out<- "./Data/Benchmarking/SD_Profiles/Output/"
getwd()
```

```{r}
#####################
## DATASET CREATION #
#####################

# Variables for income groups and regions used in the loop
# High income

# Lower MICS
country_estimates_lmics <- read.csv(paste0(dir_int, "World_SD_values.csv"))
country_estimates_lmics <- country_estimates_lmics %>% filter(income=='Lower middle income')
lmics <- unique(country_estimates_lmics$iso3)
lmics <- as.character(lmics)
```

```{r}
#country <- lmics ### HERE CHOOSE GROUP WE WANT TO COMPARE TO FROM ABOVE VARIABES ###
group <- 'lmics' ### HERE CHOOSE GROUP WE WANT TO COMPARE TO FROM ABOVE VARIABES ###

country<-c("EGY")

comparison_percentile <- paste0('DB_SD_',group,'_score')
comparison_score <- paste0('DB_SD_',group,'_score')
#i="EGY"

### Version indicator
version <- 0 #choose 0 for v1(CEO), 1 for MENA version
```


```{r}
### COUNTRY Percentile DATASET ### 
###         World              ###
country_all <- read.csv(paste0(dir_int,"World_SD_values1.csv"))

#Arrange values 
country_all$pop_dis<-as.numeric(as.character(country_all$pop_dis))
country_all$pop_dis<-format(round(country_all$pop_dis, 2), nsmall = 2)


#Assign names to variables
#Resilience
colnames(country_all)<-str_replace(colnames(country_all), "food_sec", "Food Security Index")
colnames(country_all)<-str_replace(colnames(country_all), "risk_wellbeing", "*Risk to wellbeing %")
colnames(country_all)<-str_replace(colnames(country_all), "risk_to_assets", "*Risk to asset %")
colnames(country_all)<-str_replace(colnames(country_all), "pop_dis", "*Pop. affected by disasters %")
colnames(country_all)<-str_replace(colnames(country_all), "EN.POP.SLUM.UR.ZS", "*Urban slum population %")
colnames(country_all)<-str_replace(colnames(country_all), "rain_exp", "*Rainfall shock exposure %")

#Inclusion
colnames(country_all)<-str_replace(colnames(country_all), "pov_1016", "*Poverty headcount %")
colnames(country_all)<-str_replace(colnames(country_all), "SL.TLF.CACT.FE.ZS", "Female labor part.%")
colnames(country_all)<-str_replace(colnames(country_all), "SH.STA.SMSS.ZS", "Safely managed sanitation %")
colnames(country_all)<-str_replace(colnames(country_all), "SH.H2O.SMDW.ZS", "Safely managed drinking water %")
colnames(country_all)<-str_replace(colnames(country_all), "HD.HCI.OVR", "Human Capital index")
colnames(country_all)<-str_replace(colnames(country_all), "SI.POV.GINI", "*Gini index")
colnames(country_all)<-str_replace(colnames(country_all), "SE.SEC.ENRR", "Secondary school enrollment %")
colnames(country_all)<-str_replace(colnames(country_all), "SH.IMM.IDPT", "Immunization DPT %")
colnames(country_all)<-str_replace(colnames(country_all), "account.t.d.7", "Account income, poorest 40%")
colnames(country_all)<-str_replace(colnames(country_all), "LGBT_acc", "LGBT acceptance index")
colnames(country_all)<-str_replace(colnames(country_all), "wbl", "Women, Business & Law index")
colnames(country_all)<-str_replace(colnames(country_all), "trust_ppl", "Most ppl. can be trusted %")
colnames(country_all)<-str_replace(colnames(country_all), "ref_idp", "*Refugees & IDPs index")
colnames(country_all)<-str_replace(colnames(country_all), "sec_aparat", "*Security aparatus index")

#Sustainability
#colnames(country_all)<-str_replace(colnames(country_all), "DT.TDS.DECT.GN.ZS", "Total debt service")
colnames(country_all)<-str_replace(colnames(country_all), "NY.ADJ.SVNG.GN.ZS", "Adjusted net savings %")
colnames(country_all)<-str_replace(colnames(country_all), "EN.ATM.PM25.MC.M3", "*PM2.5 mean annual exposure mg/m3")
#colnames(country_all)<-str_replace(colnames(country_all), "forest_loss", "Forest loss")
colnames(country_all)<-str_replace(colnames(country_all), "EG.FEC.RNEW.ZS", "Renewal energy consumption %")
colnames(country_all)<-str_replace(colnames(country_all), "ER.H2O.INTR.PC", "Renewal internal freshwater(pc)")
colnames(country_all)<-str_replace(colnames(country_all), "wat_qua", "Water Quality SDG 6.3")
colnames(country_all)<-str_replace(colnames(country_all), "WWT.new", "Wastewater treated %")
colnames(country_all)<-str_replace(colnames(country_all), "waste_managed", "Waste properly managed %")
colnames(country_all)<-str_replace(colnames(country_all), "waste_ratio", "*Waste generation rate (kg/pc/day)")
colnames(country_all)<-str_replace(colnames(country_all), "BHV.new", "Biodiversity & Habitat index")
colnames(country_all)<-str_replace(colnames(country_all), "FSH.new", "Fisheries index")
colnames(country_all)<-str_replace(colnames(country_all), "GIB.new", "*GHG intensity growth rate")
colnames(country_all)<-str_replace(colnames(country_all), "EN.ATM.CO2E.PC", "*CO2 emissions (mtr/ton pc)")


#Inclusion
colnames(country_all)<-str_replace(colnames(country_all), "agri_land", "Agri. land productivity $/ha")
colnames(country_all)<-str_replace(colnames(country_all), "agri_value", "Agri. value added per worker $")
colnames(country_all)<-str_replace(colnames(country_all), "gini_ghg", "Total GNI/GHG emission")
colnames(country_all)<-str_replace(colnames(country_all), "gov_effect", "Governance effectivness")
colnames(country_all)<-str_replace(colnames(country_all), "cont_corr", "Control of corruption")
colnames(country_all)<-str_replace(colnames(country_all), "reg_qua", "Regulatory quality")
colnames(country_all)<-str_replace(colnames(country_all), "lpi_score", "Logistic performance index")
colnames(country_all)<-str_replace(colnames(country_all), "sdg9_intuse", "Pop. using internet %")
colnames(country_all)<-str_replace(colnames(country_all), "water_efficiency", "Water efficiency (USD/m3)")
colnames(country_all)<-str_replace(colnames(country_all), "lpi_score", "Logistic performance index")
colnames(country_all)<-str_replace(colnames(country_all), "Tenure.security", "Tenure security index")
```


```{r}
### COUNTRY Percentile DATASET ###

for(i in country){

country_tot<-country_all  
country_tot<- country_tot[country_tot$iso3 == i, ]
country_percent<-country_tot %>% select(matches('_per'))
country_percent <- as.data.frame(t(as.matrix(country_percent)))
country_percent <- country_percent %>% rownames_to_column("indicator")
colnames(country_percent)<-c("indicator", "percentil")
country_percent$indicator<-str_replace(country_percent$indicator, "_per", "")


#### Country Data Raw values ####

country_values<-country_tot %>% select(-matches('_per'))
country_values <- as.data.frame(t(as.matrix(country_values)))
country_values <- country_values %>% rownames_to_column("indicator")
colnames(country_values)<-c("indicator", "raw_value")


#Set indicators categories

efficiency<-c("Agri. land productivity $/ha", "Agri. value added per worker $", "Total GNI/GHG emission","Governance effectivness", "Control of corruption",  "Regulatory quality", "Logistic performance index", "Pop. using internet %", "Water efficiency (USD/m3)", "Logistic performance index", "Tenure security index")

sustainability<-c("Adjusted net savings %", "*PM2.5 mean annual exposure mg/m3", "Renewal energy consumption %", "Renewal internal freshwater(pc)", "Water Quality SDG 6.3", "Wastewater treated %", "Waste properly managed %", "*Waste generation rate (kg/pc/day)", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)")

inclusion<-c("*Poverty headcount %", "*Gini index", "Immunization DPT %", "Safely managed sanitation %", "Safely managed drinking water %", "Immunization DPT %",  "Secondary school enrollment %", "Human Capital indexL", 'Account income, poorest 40%', "Female labor part.%", "Women, Business & Law index",  "LGBT acceptance index",  "Most ppl. can be trusted %", "*Refugees & IDPs index", "*Security aparatus index" )

resilience<-c("Food Security Index", "*Risk to wellbeing %", "*Risk to asset %","*Pop. affected by disasters %", "*Rainfall shock exposure %", "*Urban slum population %")


#Assign categories (number set to appear in the RISE order in the graph)

country_percent$category <- ifelse(country_percent$indicator %in% efficiency, '2.Efficiency',
                                   ifelse(country_percent$indicator %in% sustainability, '3.Sustainability',
                                          ifelse(country_percent$indicator %in% resilience, '4.Resilience', 
                                                 ifelse(country_percent$indicator %in% inclusion, '1.Inclusion', 'Other'))))

country_percent <- country_percent%>% filter(category!='Other') 

#Join percentage and raw value
country_percent <-left_join(country_percent, country_values, by="indicator")
country_percent$raw_value<-as.numeric(as.character(country_percent$raw_value))
country_percent$raw_value<-format(round(country_percent$raw_value, 2), nsmall = 2)


# Format score data for graphs
#country_percent <- country_percent[,c(3,1,2,4)]
country_percent$percentil <- as.numeric(as.character(country_percent$percentil))
country_percent$percentil<-country_percent$percentil*100
country_percent <- country_percent[order(country_percent$category),]

#create first databases for percentil ranking (global)

country_percent$percentil<-as.integer(country_percent$percentil)
country_percent<-country_percent%>% select(indicator, percentil, raw_value, category)
write.csv(country_percent,paste0(dir_out, group,'/',i,"_percentil.csv"), row.names = FALSE)


### COUNTRY SCORE DATASET ###

country_score <- read.csv(paste0(dir_int, comparison_score,".csv"))


#Assign names to variables
#Resilience
colnames(country_score)<-str_replace(colnames(country_score), "food_sec", "Food Security Index")
colnames(country_score)<-str_replace(colnames(country_score), "risk_wellbeing", "*Risk to wellbeing %")
colnames(country_score)<-str_replace(colnames(country_score), "risk_to_assets", "*Risk to asset %")
colnames(country_score)<-str_replace(colnames(country_score), "pop_dis", "*Pop. affected by disasters %")
colnames(country_score)<-str_replace(colnames(country_score), "EN.POP.SLUM.UR.ZS", "*Urban slum population %")
colnames(country_score)<-str_replace(colnames(country_score), "rain_exp", "*Rainfall shock exposure %")

#Inclusion
colnames(country_score)<-str_replace(colnames(country_score), "pov_1016", "*Poverty headcount %")
colnames(country_score)<-str_replace(colnames(country_score), "SL.TLF.CACT.FE.ZS", "Female labor part.%")
colnames(country_score)<-str_replace(colnames(country_score), "SH.STA.SMSS.ZS", "Safely managed sanitation %")
colnames(country_score)<-str_replace(colnames(country_score), "SH.H2O.SMDW.ZS", "Safely managed drinking water %")
colnames(country_score)<-str_replace(colnames(country_score), "HD.HCI.OVR", "Human Capital index")
colnames(country_score)<-str_replace(colnames(country_score), "SI.POV.GINI", "*Gini index")
colnames(country_score)<-str_replace(colnames(country_score), "SE.SEC.ENRR", "Secondary school enrollment %")
colnames(country_score)<-str_replace(colnames(country_score), "SH.IMM.IDPT", "Immunization DPT %")
colnames(country_score)<-str_replace(colnames(country_score), "account.t.d.7", "Account income, poorest 40%")
colnames(country_score)<-str_replace(colnames(country_score), "LGBT_acc", "LGBT acceptance index")
colnames(country_score)<-str_replace(colnames(country_score), "wbl", "Women, Business & Law index")
colnames(country_score)<-str_replace(colnames(country_score), "trust_ppl", "Most ppl. can be trusted %")
colnames(country_score)<-str_replace(colnames(country_score), "ref_idp", "*Refugees & IDPs index")
colnames(country_score)<-str_replace(colnames(country_score), "sec_aparat", "*Security aparatus index")

#Sustainability
#colnames(country_score)<-str_replace(colnames(country_score), "DT.TDS.DECT.GN.ZS", "Total debt service")
colnames(country_score)<-str_replace(colnames(country_score), "NY.ADJ.SVNG.GN.ZS", "Adjusted net savings %")
colnames(country_score)<-str_replace(colnames(country_score), "EN.ATM.PM25.MC.M3", "*PM2.5 mean annual exposure mg/m3")
#colnames(country_score)<-str_replace(colnames(country_score), "forest_loss", "Forest loss")
colnames(country_score)<-str_replace(colnames(country_score), "EG.FEC.RNEW.ZS", "Renewal energy consumption %")
colnames(country_score)<-str_replace(colnames(country_score), "ER.H2O.INTR.PC", "Renewal internal freshwater(pc)")
colnames(country_score)<-str_replace(colnames(country_score), "wat_qua", "Water Quality SDG 6.3")
colnames(country_score)<-str_replace(colnames(country_score), "WWT.new", "Wastewater treated %")
colnames(country_score)<-str_replace(colnames(country_score), "waste_managed", "Waste properly managed %")
colnames(country_score)<-str_replace(colnames(country_score), "waste_ratio", "*Waste generation rate (kg/pc/day)")
colnames(country_score)<-str_replace(colnames(country_score), "BHV.new", "Biodiversity & Habitat index")
colnames(country_score)<-str_replace(colnames(country_score), "FSH.new", "Fisheries index")
colnames(country_score)<-str_replace(colnames(country_score), "GIB.new", "*GHG intensity growth rate")
colnames(country_score)<-str_replace(colnames(country_score), "EN.ATM.CO2E.PC", "*CO2 emissions (mtr/ton pc)")


#Inclusion
colnames(country_score)<-str_replace(colnames(country_score), "agri_land", "Agri. land productivity $/ha")
colnames(country_score)<-str_replace(colnames(country_score), "agri_value", "Agri. value added per worker $")
colnames(country_score)<-str_replace(colnames(country_score), "gini_ghg", "Total GNI/GHG emission")
colnames(country_score)<-str_replace(colnames(country_score), "gov_effect", "Governance effectivness")
colnames(country_score)<-str_replace(colnames(country_score), "cont_corr", "Control of corruption")
colnames(country_score)<-str_replace(colnames(country_score), "reg_qua", "Regulatory quality")
colnames(country_score)<-str_replace(colnames(country_score), "lpi_score", "Logistic performance index")
colnames(country_score)<-str_replace(colnames(country_score), "sdg9_intuse", "Pop. using internet %")
colnames(country_score)<-str_replace(colnames(country_score), "water_efficiency", "Water efficiency (USD/m3)")
colnames(country_score)<-str_replace(colnames(country_score), "lpi_score", "Logistic performance index")
colnames(country_score)<-str_replace(colnames(country_score), "Tenure.security", "Tenure security index")


country_score <- country_score[country_score$iso3 == i, ]
country_score <- as.data.frame(t(as.matrix(country_score)))
country_score <- country_score %>% rownames_to_column("indicator")
colnames(country_score)<-c("indicator", "score")
country_score$category <- ifelse(country_score$indicator %in% efficiency, '2.Efficiency',
                                   ifelse(country_score$indicator %in% sustainability, '3.Sustainability',
                                          ifelse(country_score$indicator %in% resilience, '4.Resilience', 
                                                 ifelse(country_score$indicator %in% inclusion, '1.Inclusion', 'Other'))))


country_score <- country_score%>% filter(category!='Other') 

#Join percentage and raw value
country_score <-left_join(country_score, country_values, by="indicator")
country_score$raw_value<-as.numeric(as.character(country_score$raw_value))
country_score$raw_value<-format(round(country_score$raw_value, 2), nsmall = 2)

# Format score data for graphs

country_score$score <- as.numeric(as.character(country_score$score))
country_score$score<-country_score$score*100
country_score <- country_score[order(country_score$category),]

#Create the second database for graph pillars (regional/income)

#Get inversed values for score graph
country_score$score <- with(country_score, (100-score))
country_score$values <- with(country_score, (100-score))

country_score$score <- as.integer(country_score$score)
country_score$values <- as.integer(country_score$values)

write.csv(country_score, paste0(dir_out, group,'/',i,"_score_graphs.csv"), row.names = FALSE)

}
```

```{r}
for_test<-country_percent

```


```{r}
##########
# Graph overall #
##########
for(i in country){
# Create dataset
  country_percent <- read.csv(file=paste0(dir_out, group,'/',i,"_percentil.csv"), header=TRUE, sep=",")

if (version == 0){
  
country_percent<-country_percent%>% filter(indicator %nin%  c("*Security aparatus index", "Waste properly managed %", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)"))

} else {
country_percent<-country_percent%>% filter(indicator !=  "Adjusted net savings %")
}

data3<-country_percent

data3 <- data3 %>% 
  filter(!is.na(percentil))%>% 
  arrange(category, percentil)
data3$id <- seq(1, nrow(data3))

label_data3 <- data3
number_of_bar3 <- nrow(label_data3)
angle3 <- 90 - 360 * (label_data3$id-0.5) /number_of_bar3     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data3$hjust <- ifelse(angle3 < -90, 1, 0)
label_data3$angle <- ifelse(angle3 < -90, angle3+180, angle3)

# prepare a data frame for base lines
base_data3 <- data3 %>% 
  group_by(category) %>% 
  dplyr::summarize(start=min(id), end=max(id)) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
#Get category name without number at the begining
base_data3$category2<-str_replace(base_data3$category, "1.|2.|3.|4.", "")

#Paste values of the percentil
label_data3$test <- paste(data3$percentil, "-", data3$indicator)


com <- ggplot(data3) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=percentil, fill=category, colour=category), stat="identity", alpha=0.7, size=0.2) +
  #colors used in the original ppt
  #scale_fill_manual(values=c("hotpink1","gold1","steelblue2", "green3")) +
  scale_fill_manual(values=c("red2" ,"darkmagenta", "darkorange","darkcyan"))+
  scale_colour_manual(values=c("black","black", "black","black")) +
  
    
    geom_label(x = 0, y = -50, label = i, hjust=0.5, fontface="bold", size=7) +
  
  ylim(-50,120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(-3,-3,-3,-3, "cm") 
  ) +
  coord_polar() +
  
   # Add labels on top of each bar
  geom_text(data=label_data3, aes(x=id, y=percentil+2, label= str_wrap(test, width = 20), hjust=label_data3$hjust), color="black", fontface="bold",alpha=1, size=3.5, angle= label_data3$angle, inherit.aes = FALSE ) +

  # Add base line information
geom_segment(data=base_data3, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data3, aes(x = title, y = -18, label=category2), hjust=c(0.5,0.5,0.5,0.5), angle=c(-60, 15, -65, 40), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)

if (version == 0){
ggsave(com, file=paste0(dir_out, group,'/',i,"_per_v1_test.png"), width=12, height=13)
} else {
 ggsave(com, file=paste0(dir_out, group,'/',i,"_per_v2_test.png"), width=12, height=13) 
  }
} 
```

```{r}
test_score<-country_score
```

```{r}
    ##########
# Graph per pilar #
  #Sustainability
    ##########
#detach(package:plyr)
for(i in country){
# Create dataset
  country_score <- read.csv(file=paste0(dir_out, group,'/',i,"_score_graphs.csv"), header=TRUE, sep=",")

if (version == 0){
  
country_score<-country_score%>% filter(indicator %nin%  c("*Security aparatus index", "Waste properly managed %", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)"))

} else {
country_score<-country_score%>% filter(indicator !=  "Adjusted net savings %")
  
}
  
##### Sustainability #######

#Split data for graphs 
country_score_graph1 <- country_score %>% filter(category== '3.Sustainability')

data2<-country_score_graph1
data2$order <- seq(1, nrow(data2))

# Move order column to the front so it does not get rejected when transforming to long format (column necessary to keep order of dimensions for the graph)
data2 <- data2 %>% 
  filter(!is.na(score))%>%
  select(order, everything())

# Transform data in a tidy format (long format)
data2 <- stats::reshape(data2, 
                direction = "long",
                varying = c("score", "values"),
                v.names = "value",
                idvar = c("order", "indicator", "category", "raw_value"),
                timevar = "observation",
                times = 1:2)

# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(data2$observation))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(as.factor(data2$category))*nObsType*.5, ncol(data2)))
colnames(to_add) <- colnames(data2)
to_add$category <- rep(levels(as.factor(data2$category)), each=empty_bar*nObsType*.5 )
data2 <- rbind(data2, to_add)

grpid = function(x) match(x, unique(x))
data2 <- data2 %>% mutate(group_id = group_indices(., category) %>% grpid)

#To group inverse and no inverse value
data2<- data2 %>% mutate(group_order=case_when(
  group_id == 1 ~ "A",
  TRUE ~ NA_character_ # all else are NA
))

data2 <- data2[order(data2$indicator),]

data2$id <- rep( seq(1, nrow(data2)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data2 <- data2 %>% dplyr::group_by(id, indicator, raw_value) %>% dplyr::summarize(tot=sum(value))
number_of_bar2 <- nrow(label_data2)
angle2 <- 90 - 360 * (label_data2$id-0.5) /number_of_bar2     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data2$hjust <- ifelse(angle2 < -90, 1, 0)
label_data2$angle <- ifelse(angle2 < -90, angle2+180, angle2)

# prepare a data frame for base lines
base_data2 <- data2 %>% 
  group_by(group_order) %>% 
  dplyr::summarize(start=min(id), end=max(id) 
            - empty_bar
          ) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data2 <- base_data2
grid_data2$end <- grid_data2$end[ c( nrow(grid_data2), 1:nrow(grid_data2)-1)] + 1.4
grid_data2$start <- grid_data2$start - .4
#grid_data2 <- grid_data2[-1,]

#Paste categories and raw values
data2$cat <- paste(data2$observation,data2$group_order)
label_data2$ind_value<-paste(label_data2$raw_value, "-", label_data2$indicator)

s <- ggplot(data2) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=cat, colour=cat), stat="identity", alpha=0.5, size=0.2) +
  #scale_fill_manual(values=c("white","steelblue1")) +
  scale_fill_manual(values=c("white","darkorange")) +
  scale_colour_manual(values=c("black","black")) +

  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  #geom_segment(data=grid_data2, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
    geom_label(x = 0, y = 0, label = i, hjust=0.5, fontface="bold", size=10) +
    annotate("text", x = rep(max(data2$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=5 , angle=0, fontface="bold", hjust=.5) +
  
  ylim(0 , 120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(-3,-3,-3,-3, "cm") 
  ) +
  coord_polar() +
  
   # Add labels on top of each bar
  
  geom_text(data=label_data2, aes(x=id, y=tot-50, label= str_wrap(ind_value, width = 22), hjust=label_data2$hjust), color="black", fontface="bold",alpha=1, size=4.5, angle= label_data2$angle, inherit.aes = FALSE ) 


if (version == 0){
ggsave(s, file=paste0(dir_out, group,'/',i,"_score_graph_sust_v1_test.png"), width=10, height=10)
} else {
 ggsave(s, file=paste0(dir_out, group,'/',i,"_score_graph_sust_v2_test.png"), width=10, height=10) 
  }

} 
```
```{r}
    ##########
# Graph per pilar #
    ##########
#detach(package:plyr)
for(i in country){
# Create dataset
  country_score <- read.csv(file=paste0(dir_out, group,'/',i,"_score_graphs.csv"), header=TRUE, sep=",")

if (version == 0){
  
country_score<-country_score%>% filter(indicator %nin%  c("*Security aparatus index", "Waste properly managed %", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)"))

} else {
country_score<-country_score%>% filter(indicator !=  "Adjusted net savings %")
  
}
##### Inclusion #######

#Split data for graphs 
country_score_graph2 <- country_score %>% filter(category== '1.Inclusion')

data2<-country_score_graph2
data2$order <- seq(1, nrow(data2))

# Move order column to the front so it does not get rejected when transforming to long format (column necessary to keep order of dimensions for the graph)
data2 <- data2 %>% 
  filter(!is.na(score))%>%
  select(order, everything())

# Transform data in a tidy format (long format)
data2 <- stats::reshape(data2, 
                direction = "long",
                varying = c("score", "values"),
                v.names = "value",
                idvar = c("order", "indicator", "category", "raw_value"),
                timevar = "observation",
                times = 1:2)

# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(data2$observation))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(as.factor(data2$category))*nObsType*.5, ncol(data2)))
colnames(to_add) <- colnames(data2)
to_add$category <- rep(levels(as.factor(data2$category)), each=empty_bar*nObsType*.5 )
data2 <- rbind(data2, to_add)

grpid = function(x) match(x, unique(x))
data2 <- data2 %>% mutate(group_id = group_indices(., category) %>% grpid)

#To group inverse and no inverse value
data2<- data2 %>% mutate(group_order=case_when(
  group_id == 1 ~ "A",
  TRUE ~ NA_character_ # all else are NA
))

data2 <- data2[order(data2$indicator),]

data2$id <- rep( seq(1, nrow(data2)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data2 <- data2 %>% dplyr::group_by(id, indicator, raw_value) %>% dplyr::summarize(tot=sum(value))
number_of_bar2 <- nrow(label_data2)
angle2 <- 90 - 360 * (label_data2$id-0.5) /number_of_bar2     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data2$hjust <- ifelse(angle2 < -90, 1, 0)
label_data2$angle <- ifelse(angle2 < -90, angle2+180, angle2)

# prepare a data frame for base lines
base_data2 <- data2 %>% 
  group_by(group_order) %>% 
  dplyr::summarize(start=min(id), end=max(id) 
            - empty_bar
          ) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data2 <- base_data2
grid_data2$end <- grid_data2$end[ c( nrow(grid_data2), 1:nrow(grid_data2)-1)] + 1.4
grid_data2$start <- grid_data2$start - .4
#grid_data2 <- grid_data2[-1,]

#Paste categories and raw values
data2$cat <- paste(data2$observation,data2$group_order)
label_data2$ind_value<-paste(label_data2$raw_value, "-", label_data2$indicator)

inc <- ggplot(data2) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=cat, colour=cat), stat="identity", alpha=0.5, size=0.2) +
  #scale_fill_manual(values=c("white","hotpink1")) +
  scale_fill_manual(values=c("white","red2")) +
  scale_colour_manual(values=c("black","black")) +

  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  #geom_segment(data=grid_data2, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
    geom_label(x = 0, y = 0, label = i, hjust=0.5, fontface="bold", size=10) +
    annotate("text", x = rep(max(data2$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=5 , angle=0, fontface="bold", hjust=.5) +
  
  ylim(0 , 120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(-3,-3,-3,-3, "cm") 
  ) +
  coord_polar() +
  
   # Add labels on top of each bar
  
  geom_text(data=label_data2, aes(x=id, y=tot-50, label= str_wrap(ind_value, width = 22), hjust=label_data2$hjust), color="black", fontface="bold",alpha=1, size=4.5, angle= label_data2$angle, inherit.aes = FALSE ) 


if (version == 0){
ggsave(inc, file=paste0(dir_out, group,'/',i,"_score_graph_incl_v1_test.png"), width=10, height=10)
} else {
 ggsave(inc, file=paste0(dir_out, group,'/',i,"_score_graph_incl_v2_test.png"), width=10, height=10) 
  }
}
```

```{r}
    ##########
# Graph per pilar #
    ##########
#detach(package:plyr)
for(i in country){
# Create dataset
  country_score <- read.csv(file=paste0(dir_out, group,'/',i,"_score_graphs.csv"), header=TRUE, sep=",")

if (version == 0){
  
country_score<-country_score%>% filter(indicator %nin%  c("*Security aparatus index", "Waste properly managed %", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)"))

} else {
country_score<-country_score%>% filter(indicator !=  "Adjusted net savings %")
  
}
##### Inclusion #######

#Split data for graphs 
country_score_graph2 <- country_score %>% filter(category== '2.Efficiency')

data2<-country_score_graph2
data2$order <- seq(1, nrow(data2))

# Move order column to the front so it does not get rejected when transforming to long format (column necessary to keep order of dimensions for the graph)
data2 <- data2 %>% 
  filter(!is.na(score))%>%
  select(order, everything())

# Transform data in a tidy format (long format)
data2 <- stats::reshape(data2, 
                direction = "long",
                varying = c("score", "values"),
                v.names = "value",
                idvar = c("order", "indicator", "category", "raw_value"),
                timevar = "observation",
                times = 1:2)

# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(data2$observation))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(as.factor(data2$category))*nObsType*.5, ncol(data2)))
colnames(to_add) <- colnames(data2)
to_add$category <- rep(levels(as.factor(data2$category)), each=empty_bar*nObsType*.5 )
data2 <- rbind(data2, to_add)

grpid = function(x) match(x, unique(x))
data2 <- data2 %>% mutate(group_id = group_indices(., category) %>% grpid)

#To group inverse and no inverse value
data2<- data2 %>% mutate(group_order=case_when(
  group_id == 1 ~ "A",
  TRUE ~ NA_character_ # all else are NA
))

data2 <- data2[order(data2$indicator),]

data2$id <- rep( seq(1, nrow(data2)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data2 <- data2 %>% dplyr::group_by(id, indicator, raw_value) %>% dplyr::summarize(tot=sum(value))
number_of_bar2 <- nrow(label_data2)
angle2 <- 90 - 360 * (label_data2$id-0.5) /number_of_bar2     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data2$hjust <- ifelse(angle2 < -90, 1, 0)
label_data2$angle <- ifelse(angle2 < -90, angle2+180, angle2)

# prepare a data frame for base lines
base_data2 <- data2 %>% 
  group_by(group_order) %>% 
  dplyr::summarize(start=min(id), end=max(id) 
            - empty_bar
          ) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data2 <- base_data2
grid_data2$end <- grid_data2$end[ c( nrow(grid_data2), 1:nrow(grid_data2)-1)] + 1.4
grid_data2$start <- grid_data2$start - .4
#grid_data2 <- grid_data2[-1,]

#Paste categories and raw values
data2$cat <- paste(data2$observation,data2$group_order)
label_data2$ind_value<-paste(label_data2$raw_value, "-", label_data2$indicator)

e <- ggplot(data2) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=cat, colour=cat), stat="identity", alpha=0.5, size=0.2) +
  #scale_fill_manual(values=c("white","gold1")) +
  scale_fill_manual(values=c("white","darkmagenta")) +
  scale_colour_manual(values=c("black","black")) +

  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  #geom_segment(data=grid_data2, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
    geom_label(x = 0, y = 0, label = i, hjust=0.5, fontface="bold", size=10) +
    annotate("text", x = rep(max(data2$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=5 , angle=0, fontface="bold", hjust=.5) +
  
  ylim(0 , 120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(-3,-3,-3,-3, "cm") 
  ) +
  coord_polar() +
  
   # Add labels on top of each bar
  
  geom_text(data=label_data2, aes(x=id, y=tot-50, label= str_wrap(ind_value, width = 22), hjust=label_data2$hjust), color="black", fontface="bold",alpha=1, size=4.5, angle= label_data2$angle, inherit.aes = FALSE ) 


if (version == 0){
ggsave(e, file=paste0(dir_out, group,'/',i,"_score_graph_eff_v1_test.png"), width=10, height=10)
} else {
 ggsave(e, file=paste0(dir_out, group,'/',i,"_score_graph_eff_v2_test.png"), width=10, height=10) 
  }
}
```

```{r}
    ##########
# Graph per pilar #
    ##########
#detach(package:plyr)
for(i in country){
# Create dataset
  country_score <- read.csv(file=paste0(dir_out, group,'/',i,"_score_graphs.csv"), header=TRUE, sep=",")

if (version == 0){
  
country_score<-country_score%>% filter(indicator %nin%  c("*Security aparatus index", "Waste properly managed %", "Biodiversity & Habitat index", "Fisheries index", "*GHG intensity growth rate", "*CO2 emissions (mtr/ton pc)"))

} else {
country_score<-country_score%>% filter(indicator !=  "Adjusted net savings %")
  
}
##### Inclusion #######

#Split data for graphs 
country_score_graph2 <- country_score %>% filter(category== '4.Resilience')

data2<-country_score_graph2
data2$order <- seq(1, nrow(data2))

# Move order column to the front so it does not get rejected when transforming to long format (column necessary to keep order of dimensions for the graph)
data2 <- data2 %>% 
  filter(!is.na(score))%>%
  select(order, everything())

# Transform data in a tidy format (long format)
data2 <- stats::reshape(data2, 
                direction = "long",
                varying = c("score", "values"),
                v.names = "value",
                idvar = c("order", "indicator", "category", "raw_value"),
                timevar = "observation",
                times = 1:2)

# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(data2$observation))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(as.factor(data2$category))*nObsType*.5, ncol(data2)))
colnames(to_add) <- colnames(data2)
to_add$category <- rep(levels(as.factor(data2$category)), each=empty_bar*nObsType*.5 )
data2 <- rbind(data2, to_add)

grpid = function(x) match(x, unique(x))
data2 <- data2 %>% mutate(group_id = group_indices(., category) %>% grpid)

#To group inverse and no inverse value
data2<- data2 %>% mutate(group_order=case_when(
  group_id == 1 ~ "A",
  TRUE ~ NA_character_ # all else are NA
))

data2 <- data2[order(data2$indicator),]

data2$id <- rep( seq(1, nrow(data2)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data2 <- data2 %>% dplyr::group_by(id, indicator, raw_value) %>% dplyr::summarize(tot=sum(value))
number_of_bar2 <- nrow(label_data2)
angle2 <- 90 - 360 * (label_data2$id-0.5) /number_of_bar2     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data2$hjust <- ifelse(angle2 < -90, 1, 0)
label_data2$angle <- ifelse(angle2 < -90, angle2+180, angle2)

# prepare a data frame for base lines
base_data2 <- data2 %>% 
  group_by(group_order) %>% 
  dplyr::summarize(start=min(id), end=max(id) 
            - empty_bar
          ) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data2 <- base_data2
grid_data2$end <- grid_data2$end[ c( nrow(grid_data2), 1:nrow(grid_data2)-1)] + 1.4
grid_data2$start <- grid_data2$start - .4
#grid_data2 <- grid_data2[-1,]

#Paste categories and raw values
data2$cat <- paste(data2$observation,data2$group_order)
label_data2$ind_value<-paste(label_data2$raw_value, "-", label_data2$indicator)

r <- ggplot(data2) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=cat, colour=cat), stat="identity", alpha=0.5, size=0.2) +
  #scale_fill_manual(values=c("white","green3")) +
  scale_fill_manual(values=c("white","darkcyan")) +
  scale_colour_manual(values=c("black","black")) +

  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  #geom_segment(data=grid_data2, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data2, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
    geom_label(x = 0, y = 0, label = i, hjust=0.5, fontface="bold", size=10) +
    annotate("text", x = rep(max(data2$id),5), y = c(20, 40, 60, 80, 100), label = c("20", "40", "60", "80", "100") , color="grey", size=5 , angle=0, fontface="bold", hjust=.5) +
  
  ylim(0 , 120) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(-3,-3,-3,-3, "cm") 
  ) +
  coord_polar() +
  
   # Add labels on top of each bar
  
  geom_text(data=label_data2, aes(x=id, y=tot-50, label= str_wrap(ind_value, width = 22), hjust=label_data2$hjust), color="black", fontface="bold",alpha=1, size=4.5, angle= label_data2$angle, inherit.aes = FALSE ) 


if (version == 0){
ggsave(r, file=paste0(dir_out, group,'/',i,"_score_graph_res_v1_test.png"), width=10, height=10)
} else {
 ggsave(r, file=paste0(dir_out, group,'/',i,"_score_graph_res_v2_test.png"), width=10, height=10) 
  }
}
```
