---
title: "Benchmarking V2"
author: "Evelyn Sanchez"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/eves/Dropbox/MENA/")
```


```{r}
library(WDI)
library(dplyr)
library(plyr)
library(readxl)
library(rvest)
library(tidyverse)
library(countrycode)
library(readxlsb)
```

#Set Directories
```{r}
dir_raw<-"./Data/Benchmarking/SD_Profiles/Raw indicators/"
dir_int<- "./Data/Benchmarking/SD_Profiles/Integrated data/"
getwd()
```

```{r}
######################
### WDI INDICATORS ###
######################

# WDI indicators
ind<-c('EN.POP.SLUM.UR.ZS', 'SL.TLF.CACT.FE.ZS', 'SH.STA.SMSS.ZS', 'SH.H2O.SMDW.ZS', 'HD.HCI.OVRL', 'SI.POV.GINI', 'SE.SEC.ENRR', 'SH.IMM.IDPT', 'account.t.d.7', 'NY.ADJ.SVNG.GN.ZS', 'EN.ATM.PM25.MC.M3', 'EG.FEC.RNEW.ZS', 'ER.H2O.INTR.PC', 'EN.ATM.GHGT.KT.CE', 'NY.GNP.MKTP.CD', 'EN.ATM.CO2E.PC')

#Group indicator by year of data 
ind_12<-c('NY.GNP.MKTP.CD', 'EN.ATM.GHGT.KT.CE')
ind_14<-c('EN.POP.SLUM.UR.ZS', 'ER.H2O.INTR.PC')
#2015= EG.FEC.RNEW.ZS
#2010-2016= SI.POV.DDAY
ind_17<-c('SL.TLF.CACT.FE.ZS', 'SH.STA.SMSS.ZS', 'SH.H2O.SMDW.ZS', 'HD.HCI.OVRL','EN.ATM.PM25.MC.M3', 'NY.ADJ.SVNG.GN.ZS') 
ind_18<-c('SH.IMM.IDPT')
ind_15_19<-c('SI.POV.GINI', 'SE.SEC.ENRR')

#Create a List with all countries (select any indicator for this)
all_countries<- WDI(country = "all", indicator = 'SL.TLF.CACT.FE.ZS', start = 1990, end = 2020, extra = TRUE, cache = NULL)
all_countries <- all_countries %>% group_by(iso2c) %>%
  filter(year==max(year))
all_countries <- subset(all_countries, select = -c(iso2c,year,capital,longitude,SL.TLF.CACT.FE.ZS, latitude,lending))
colnames(all_countries)[colnames(all_countries)=="iso3c"] <- "iso3"
all_countries<-all_countries%>%filter(region != "Aggregates")

# Importation and cleaning of each WDI indicator
for(i in ind){
  print(i)
  if (i == 'account.t.d.7'){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi<-subset(wdi, !is.na(account.t.d.7))
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2017)
  wdi <- subset(wdi, select = -c(iso3c, region, income,year,region, capital,longitude,latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso2c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i %in% ind_15_19){
  wdi <- WDI(country = "all", indicator = i, start = 2015, end = 2019, extra = TRUE, cache = NULL)
  wdi <- na.omit(wdi)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==max(year))
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude, income, region,  year, latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i %in% ind_12){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2012)
  wdi <- na.omit(wdi)
  wdi <- subset(wdi, select = -c(iso2c,capital,year, income, region, longitude,latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i %in% ind_14){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- na.omit(wdi)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2014)
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude,year,region, income,latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i == 'EG.FEC.RNEW.ZS'){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2015)
  wdi <- na.omit(wdi)
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude,year, region, latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i == 'EN.ATM.CO2E.PC'){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2016)
  wdi <- na.omit(wdi)
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude,year, region, latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i %in% ind_17){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year== 2017)
  wdi <- na.omit(wdi)
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude,year, income, latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
  }
  if (i %in% ind_18){
  wdi <- WDI(country = "all", indicator = i, start =2000, end =2020, extra = TRUE, cache = NULL)
  wdi <- wdi %>% group_by(iso2c) %>% filter(year==2018)
  wdi <- na.omit(wdi)
  wdi <- subset(wdi, select = -c(iso2c,capital,longitude,year, income,region, latitude,lending,country))
  colnames(wdi)[colnames(wdi)=="iso3c"] <- "iso3"
  assign(paste('wdi_',i,sep=''),wdi)
    }
}

#Poverty Average 2010- 2016
wdi <- WDI(country = "all", indicator = 'SI.POV.DDAY', start =2010, end =2016, extra = TRUE, cache = NULL)
poverty<- wdi%>%
  group_by(iso3c)%>%
  dplyr::summarize(mean(SI.POV.DDAY, na.rm = TRUE))
  colnames(poverty)<-c("iso3", "pov_1016")
```

#Indicatord by web scraping 
```{r}
#####  WGI #####
#All indicators from WGI
#Gov effciency
temp <- tempfile()
download.file("http://info.worldbank.org/governance/wgi/Home/downLoadFile?fileName=wgidataset.xlsx", temp, mode="wb")
effect <- read_excel((temp), sheet = "GovernmentEffectiveness", skip = 14)
effect<-  subset(effect, select= c("Code", "Estimate...117"))   #Estimate...123 for 2019    #get the last estimated year
colnames(effect)<-c("iso3", "gov_effect")
effect$gov_effect<- as.numeric(as.character(effect$gov_effect))

#Control of corruption
corr <- read_excel((temp), sheet = "ControlofCorruption", skip = 14)
corr <-  subset(corr, select= c("Code", "Estimate...117"))        #Estimate...123 for 2019    #get the last estimated year
colnames(corr)<-c("iso3", "cont_corr")
corr$cont_corr<- as.numeric(as.character(corr$cont_corr))

#RegulatoryQuality
regq <- read_excel((temp), sheet = "RegulatoryQuality", skip = 14)
regq <-  subset(regq, select= c("Code", "Estimate...117"))   #Estimate...123 for 2019    #get the last estimated year
colnames(regq)<-c("iso3", "reg_qua")
regq$reg_qua<- as.numeric(as.character(regq$reg_qua))

###### Population using internet  ######
temp1 <- tempfile()
download.file("https://sdsna.github.io/SDR2020/SDR2020Database.xlsx", temp1, mode="wb")
internet <- read_excel((temp1), sheet = "Raw Trend Data")
internet<-internet%>%
  select(Country, id, Year,sdg9_intuse)%>%
  group_by(Country)%>%
  filter(Year==2017)
colnames(internet)[colnames(internet)=="id"] <- "iso3"
internet<-internet%>%ungroup()%>%select(iso3, sdg9_intuse)

#####  Water efficiency (For update, replace download link from : http://www.fao.org/sustainable-development-goals/indicators/641/en/) ######
temp2 <- tempfile()
download.file("https://sdlc.fao.org/artifactory/fao-sdg-releases/6.4.1/6_4_1_May_2020.xlsx", temp2, mode="wb")
water_efficiency <- read_excel((temp2))
water_efficiency$iso3<-countrycode(water_efficiency$GeoAreaName, origin = 'country.name', destination = 'iso3c')
water_efficiency<-water_efficiency%>%
  group_by(GeoAreaName)%>%
  filter(TimePeriod==2017)%>%
  ungroup()%>%
  select(iso3, Value)
water_efficiency$Value<-as.character(as.numeric(water_efficiency$Value))
colnames(water_efficiency)[colnames(water_efficiency)=="Value"] <- "water_efficiency"


##### EPI mesures ######
#(Biodiverity and Habitat,Wastewater that receives treatment, Fisheries index  Greenhouse gas intensity growth rate) 

temp3 <- tempfile()
download.file("https://epi.yale.edu/downloads/epi2020results20200604.csv", temp3, mode="wb")
epi_indices<-read.csv(temp3)
# 0 in this indicators means no data, so replace 0 with NA
epi_indices<-epi_indices%>%
  select(iso, WWT.new,  BHV.new, FSH.new, GIB.new )%>% 
  mutate_if(is.numeric, ~replace(., . == 0, NA))
colnames(epi_indices)[colnames(epi_indices)=="iso"] <- "iso3"

###### Fragility State Index #######
temp4 <- tempfile()
download.file("https://fragilestatesindex.org/wp-content/uploads/2020/05/fsi-2020.xlsx", temp4, mode="wb")
frag_index <- read_excel((temp4))
frag_index$iso3<-countrycode(frag_index$Country, origin = 'country.name', destination = 'iso3c')
frag_index<-frag_index%>%select("iso3","C1: Security Apparatus", "S2: Refugees and IDPs")
colnames(frag_index)<-c("iso3", "sec_aparat", "ref_idp" )

###### Women, Business, Law ###
temp5 <- tempfile()
download.file("http://pubdocs.worldbank.org/en/625831591105047863/WBL-50YearPanelDetails-Web-01Jun2020.xlsx", temp5, mode="wb")
women <- read_excel(temp5, sheet = "WBL2020", skip= 1)
#Correct country code for West Bank and Gaza
women$Code[women$Economy=="West Bank and Gaza"] <- "PSE"
women<-  subset(women, select= c("Code", "WBL INDEX"))
colnames(women)<-c("iso3", "wbl")
```
#Indicators in excel and csv datasets
```{r}
#Read csv
temp <- list.files(path= dir_raw, pattern = "*.csv")
  file_names <- make.names(gsub("*.csv", "", temp))
  list2env(
    lapply(setNames(paste0(dir_raw, temp), file_names),
           read.csv), envir = .GlobalEnv)
#Read excel
temp <- list.files(path= dir_raw, pattern = "*.xlsx|*.xls")
temp<-temp[2:8]
file_names <- make.names(gsub("*.xlsx|*.xls", "", temp))
  list2env(
    lapply(setNames(paste0(dir_raw, temp), file_names),
           read_excel), envir = .GlobalEnv)
  
### Risk Unbreakable dataset #####
Unbreakable_global$iso3<-countrycode(Unbreakable_global$country, origin = 'country.name', destination = 'iso3c')
risk<-  subset(Unbreakable_global, select= c(iso3, risk, risk_to_assets))
risk$risk_wellbeing<-risk$risk*100
risk$risk_to_assets<-risk$risk_to_assets*100
risk$risk<-NULL
  
### Agricultural value FAO dataset http://www.fao.org/faostat/en/#data/OE ####
FAOSTAT_data_10.23.2020$iso3<-countrycode(FAOSTAT_data_10.23.2020$Area, origin = 'country.name', destination = 'iso3c')
agri_value<-  subset(FAOSTAT_data_10.23.2020, select= c("iso3", "Value"))
colnames(agri_value)<-c("iso3", "agri_value")
  
#land_tenure from https://www.prindex.net/data/
Land_tenure$iso3<-countrycode(Land_tenure$Name, origin = 'country.name', destination = 'iso3c')
Land_tenure<-Land_tenure%>%select(iso3, Tenure.security)

#Waste production: Jambeck et al data
Jambeck_et_al_data$iso3<-countrycode(Jambeck_et_al_data$Country, origin = 'country.name', destination = 'iso3c')
Jambeck_et_al_data$iso3[Jambeck_et_al_data$Country=="Channel Islands"] <- "CHI"
Jambeck_et_al_data<-Jambeck_et_al_data%>%select("Waste generation rate [kg/person/day]3", "% Inadequately managed waste5", "iso3")
colnames(Jambeck_et_al_data)<-c("waste_ratio", "waste_missmanaged", "iso3")
Jambeck_et_al_data$waste_managed<-100-Jambeck_et_al_data$waste_missmanaged
Jambeck_et_al_data$waste_missmanaged<-NULL

#Logistic index from #https://lpi.worldbank.org/ (error in the file when use web scraping)
lpi_aggregated_ranks$iso3<-countrycode(lpi_aggregated_ranks$Country, origin = 'country.name', destination = 'iso3c')
lpi_aggregated_ranks<-lpi_aggregated_ranks%>%select("LPI Score", "iso3")
colnames(lpi_aggregated_ranks)<-c("lpi_score", "iso3")

#Confidence in gov from Gallup World Values survey
Confidence_The_Government<-Confidence_The_Government[6:8,]
Confidence_The_Government <- as.data.frame(t(as.matrix(Confidence_The_Government)))
Confidence_The_Government<-Confidence_The_Government[-c(1:2),]
Confidence_The_Government$V2 <-as.numeric(as.character(Confidence_The_Government$V2))
Confidence_The_Government$V3 <-as.numeric(as.character(Confidence_The_Government$V3))
Confidence_The_Government<-Confidence_The_Government%>% mutate(conf_gov = V2 + V3)
Confidence_The_Government$iso3<-countrycode(Confidence_The_Government$V1, origin = 'country.name', destination = 'iso3c')
Confidence_The_Government<-Confidence_The_Government%>% select('iso3', 'conf_gov')

#Trust people from Gallup World Values survey
Most_people_can_be_trusted<-Most_people_can_be_trusted[6:7,]
Most_people_can_be_trusted <- as.data.frame(t(as.matrix(Most_people_can_be_trusted)))
Most_people_can_be_trusted<-Most_people_can_be_trusted[-c(1:2),]
Most_people_can_be_trusted$iso3<-countrycode(Most_people_can_be_trusted$V1, origin = 'country.name', destination = 'iso3c')
Most_people_can_be_trusted<-Most_people_can_be_trusted%>% select('iso3', 'V2')
colnames(Most_people_can_be_trusted)<-c('iso3', 'trust_ppl')
Most_people_can_be_trusted$trust_ppl<-as.numeric(as.character(Most_people_can_be_trusted$trust_ppl))

#Agr land productivity $, 2016
FAO.land.productivity$iso3<-countrycode(FAO.land.productivity$Country, origin = 'country.name', destination = 'iso3c')
FAO.land.productivity$iso3[FAO.land.productivity$Country=="Channel Islands"] <- "CHI"
FAO.land.productivity<-FAO.land.productivity%>% select('iso3', '2016')
colnames(FAO.land.productivity)<-c('iso3', 'agri_land')

  ####  Indicators from master data (Calculation from the CEO) ####

#LGBT - Manually collected from https://williamsinstitute.law.ucla.edu/wp-content/uploads/Global-Acceptance-Index-LGBT-Oct-2019.pdf
#Rainfall shock exposure % & Pop affected by disasters % 
#water quality
#Food security index, 2019
#Forest loss%, 2001-2019
#Pop affected %
#Rainfall exp 
  
master<-read_excel(paste0(dir_raw, "SD GG Diagnostics - Database V7.xlsx"), sheet = "Master2")
master <-  subset(master, select= c("Country Name",  "LGBT acceptance index", "Water quality", "Food security index, 2019", "Forest loss%, 2001-2019", "*Pop affected %", "*Rainfall exp %"))
colnames(master)<-c("Country",  "LGBT_acc", "wat_qua", "food_sec", "forest_loss", "pop_dis", "rain_exp")
master$iso3<-countrycode(master$Country, origin = 'country.name', destination = 'iso3c')

#Multiply by 100 percentage variables
master$pop_dis<-master$pop_dis*100
master$rain_exp<-master$rain_exp*100
master$forest_loss<-master$forest_loss*100

#Correct Kosovo and Channel Islands
master$iso3[master$Country=="Kosovo"] <- "XKX"
master$iso3[master$Country=="Channel Islands"] <- "CHI"
master$Country<-NULL

```

#Correct country classification from the WDI
```{r}
#Check countries income classifications are accurate 
classification<-read_excel(paste0(dir_raw, "SD GG Diagnostics - Database V7.xlsx"), sheet = "List of economies", skip= 3)
classification<-classification%>%
  select(Economy, Code, 'Income group' )
match<-left_join(all_countries, classification, by=c("iso3"="Code"))
match<-match%>%
  filter(income!= "Aggregates")
diff <- match[match$'Income group'!=match$income, ]
#diff$region<-NULL
#diff$Region<-NULL
#Correct income groups from the WDI data (before joining)
#https://blogs.worldbank.org/opendata/new-world-bank-country-classifications-income-level-2020-2021
all_countries$income[all_countries$iso3=="DZA"] <- "Lower middle income"
all_countries$income[all_countries$iso3=="IDN"] <- "Upper middle income"
all_countries$income[all_countries$iso3=="LKA"] <- "Lower middle income"
all_countries$income[all_countries$iso3=="MUS"] <- "High income"
all_countries$income[all_countries$iso3=="NPL"] <- "Lower middle income"
all_countries$income[all_countries$iso3=="NRU"] <- "High income"
all_countries$income[all_countries$iso3=="SDN"] <- "Low income"
all_countries$income[all_countries$iso3=="TZA"] <- "Lower middle income"
## Other countries that changed category according to: https://blogs.worldbank.org/opendata/new-world-bank-country-classifications-income-level-2020-2021
all_countries$income[all_countries$iso3=="ROU"] <- "High income"
all_countries$income[all_countries$iso3=="BEN"] <- "Lower middle income"
```


```{r}
#### Merge ####

#Join all indicators
ind2 <- list(all_countries, wdi_EG.FEC.RNEW.ZS, wdi_EN.POP.SLUM.UR.ZS, wdi_SL.TLF.CACT.FE.ZS, wdi_SH.STA.SMSS.ZS, wdi_SH.H2O.SMDW.ZS, wdi_HD.HCI.OVRL, wdi_SI.POV.GINI, wdi_SE.SEC.ENRR, wdi_SH.IMM.IDPT, wdi_account.t.d.7, wdi_NY.ADJ.SVNG.GN.ZS, wdi_EN.ATM.PM25.MC.M3, wdi_ER.H2O.INTR.PC, wdi_NY.GNP.MKTP.CD, wdi_EN.ATM.GHGT.KT.CE, wdi_EN.ATM.CO2E.PC, poverty, effect, corr, regq, internet, water_efficiency, epi_indices, frag_index, women, risk, agri_value, Land_tenure, Jambeck_et_al_data, lpi_aggregated_ranks, Confidence_The_Government, Most_people_can_be_trusted, FAO.land.productivity, master)


#library(plyr)
integrated <- join_all(ind2, type = "left", match = "first") 
integrated <- integrated %>% select(country, everything())


###Create GNI/GHG ######
#NY.GNP.MKTP.CD/ EN.ATM.GHGT.KT.CE
integrated$gini_ghg<-integrated$NY.GNP.MKTP.CD/integrated$EN.ATM.GHGT.KT.CE


write.csv(integrated, paste0(dir_int, "Integrated.csv"), row.names = FALSE)
integrated<-read.csv(paste0(dir_int, "Integrated.csv"))

#Filter by the list of countries in the Master list
list_countries<-master$iso3  
integrated2<-integrated%>%
  filter(iso3 %in% list_countries)


#Clean working space
rm(list=setdiff(ls(), c("dir_int", "dir_raw", "integrated", "integrated2", "master", "list_countries")))
```

#### Scores ######
```{r}
#Two-sided case: Higher value is better performance, but indicator can take on negative values
#colnames(integrated2)
two_side<-c('country', "iso3", "region", "income",  "food_sec", "SL.TLF.CACT.FE.ZS","SH.H2O.SMDW.ZS", "SH.H2O.SMDW.ZS", "SH.STA.SMSS.ZS", "HD.HCI.OVRL", "SE.SEC.ENRR", "SH.IMM.IDPT", "account.t.d.7", "LGBT_acc", "wbl", "conf_gov", "trust_ppl", "NY.ADJ.SVNG.GN.ZS", "EG.FEC.RNEW.ZS", "ER.H2O.INTR.PC", "wat_qua",  "agri_value", "agri_land", "gini_ghg", "cont_corr", "gov_effect", "reg_qua", "lpi_score", "WWT.new", "waste_managed", "BHV.new", "FSH.new", "sdg9_intuse", "water_efficiency",   "Tenure.security")

#Inverted case: Higher value is worse performance, (no negative)
inv_side<- c('country', "iso3", "region", "income", "risk_to_assets", "risk_wellbeing", "pop_dis",  "rain_exp", "EN.POP.SLUM.UR.ZS", "pov_1016", "SI.POV.GINI", "EN.ATM.PM25.MC.M3", "forest_loss", "ref_idp", "sec_aparat", "waste_ratio", "GIB.new",  "EN.ATM.CO2E.PC") 
```

###### Score Formulas For Income  Groups######
```{r}
#detach plyr or the formulas won't work 
detach(package:plyr) 
#Indicators - Higher value = better performance
scores_nor <- function(data, y){
  data <- data[colnames(data) %in% two_side]
  data %>%
    mutate(across(where(is.numeric), function(x){
    (min(x, na.rm=TRUE) - x)/
      (min(x, na.rm=TRUE) - max(x[which(.$income == y)], na.rm=TRUE))}))
}

#Indicators- Higher value= worst performance
scores_inv <- function(data, y){
  data <- data[colnames(data) %in% inv_side]
  data %>%
    mutate(across(where(is.numeric), function(x){
    (max(x, na.rm=TRUE) - x)/
      (max(x, na.rm=TRUE) - min(x[which(.$income == y)], na.rm=TRUE))}))
}
```

###### Score Formulas for Regional Comparison  ######
```{r}

#Indicators - Higher value = better performance
scores_reg_nor <- function(data, y){
  data <- data[colnames(data) %in% two_side]
  data %>%
    mutate(across(where(is.numeric), function(x){
    (min(x, na.rm=TRUE) - x)/
      (min(x, na.rm=TRUE) - max(x[which(.$region == y)], na.rm=TRUE))}))
}

#Indicators- Higher value= worst performance
scores_reg_inv <- function(data, y){
  data <- data[colnames(data) %in% inv_side]
  data %>%
    mutate(across(where(is.numeric), function(x){
    (max(x, na.rm=TRUE) - x)/
      (max(x, na.rm=TRUE) - min(x[which(.$region == y)], na.rm=TRUE))}))
}
```
#Calculate Percentile Rank
```{r}
#____________________#
#_ Percentile Rank _#
#____________________#

#inverse per ranking
per_inv <- function(x) {
  y = (1- percent_rank(x))
}

#Get percentile for normal variables
vars_nor<-two_side[-(1:4)]
vars_nor <- setNames(vars_nor, paste0(vars_nor, "_per")) # create new column names
integrated2 <- integrated2 %>% 
  mutate_each_(funs(percent_rank), vars_nor)

#Get percentile for inverse variables
vars_inv<-inv_side[-(1:4)]
vars_inv <- setNames(vars_inv, paste0(vars_inv, "_per")) # create new column names
integrated2 <- integrated2 %>% 
  mutate_each_(funs(per_inv), vars_inv)

#check value of columns (percentiles)

#summary(integrated2)
```


```{r}
#______________________#
#_  Pilars Percentil _  #
#______GLOBAL_________#

integrated3<-integrated2
#colnames(integrated3)

# Resilence
integrated3<-mutate(integrated3, Resiliance_v1 = rowMeans(select(integrated3, c("risk_wellbeing_per", "risk_to_assets_per", "food_sec_per", "pop_dis_per", "rain_exp_per", "EN.POP.SLUM.UR.ZS_per")), na.rm = TRUE))

integrated3<-mutate(integrated3, Resiliance_v2 = rowMeans(select(integrated3, c("risk_wellbeing_per", "risk_to_assets_per", "food_sec_per", "pop_dis_per", "rain_exp_per", "EN.POP.SLUM.UR.ZS_per")), na.rm = TRUE))

#Inclusion
integrated3<-mutate(integrated3, Inclusion_v1 = rowMeans(select(integrated3, c("pov_1016_per", 'SL.TLF.CACT.FE.ZS_per',"SH.STA.SMSS.ZS_per", "SH.H2O.SMDW.ZS_per", "HD.HCI.OVRL_per", "SI.POV.GINI_per", "SE.SEC.ENRR_per", "SH.IMM.IDPT_per", "account.t.d.7_per", "LGBT_acc_per", "wbl_per", "trust_ppl_per", "ref_idp_per")), na.rm = TRUE))

#No included: "conf_gov_per", "sec_aparat"

integrated3<-mutate(integrated3, Inclusion_v2 = rowMeans(select(integrated3, c("pov_1016_per", 'SL.TLF.CACT.FE.ZS_per',"SH.STA.SMSS.ZS_per", "SH.H2O.SMDW.ZS_per", "HD.HCI.OVRL_per", "SI.POV.GINI_per", "SE.SEC.ENRR_per", "SH.IMM.IDPT_per", "account.t.d.7_per", "LGBT_acc_per", "wbl_per", "trust_ppl_per", "ref_idp_per", "sec_aparat_per")), na.rm = TRUE))
#No included: "conf_gov_per"  


#Sustainability
integrated3<-mutate(integrated3, Sustainability_v1 = rowMeans(select(integrated3, c("NY.ADJ.SVNG.GN.ZS_per", "EN.ATM.PM25.MC.M3_per", "EG.FEC.RNEW.ZS_per", "ER.H2O.INTR.PC_per","wat_qua_per", "WWT.new_per", "waste_ratio_per" )), na.rm = TRUE))

#No included: "forest_loss_per","DT.TDS.DECT.GN.ZS_per","waste_managed_per, BHV_new_per", "FSH_new_per", "GIB_new_per", "EN.ATM.CO2E.PC_per"

integrated3<-mutate(integrated3, Sustainability_v2 = rowMeans(select(integrated3, c("EN.ATM.PM25.MC.M3_per", "EG.FEC.RNEW.ZS_per", "ER.H2O.INTR.PC_per","wat_qua_per", "WWT.new_per", "waste_ratio_per", "waste_managed_per", "BHV.new_per", "FSH.new_per", "GIB.new_per", "EN.ATM.CO2E.PC_per")), na.rm = TRUE))
#"forest_loss_per""DT.TDS.DECT.GN.ZS_per", "NY.ADJ.SVNG.GN.ZS_per"

#Efficiency 

integrated3<-mutate(integrated3, Efficiency_v1 = rowMeans(select(integrated3, c("agri_value_per", "agri_land_per", "gini_ghg_per", "gov_effect_per", "cont_corr_per", "reg_qua_per", "lpi_score_per", "sdg9_intuse_per", "water_efficiency_per", "Tenure.security_per")), na.rm = TRUE))

integrated3<-mutate(integrated3, Efficiency_v2 = rowMeans(select(integrated3, c("agri_value_per", "agri_land_per", "gini_ghg_per", "gov_effect_per", "cont_corr_per", "reg_qua_per", "lpi_score_per", "sdg9_intuse_per", "water_efficiency_per", "Tenure.security_per")), na.rm = TRUE))

#Save all the World Values

write.csv(integrated3, paste0(dir_int, "World_SD_values1.csv"), row.names = FALSE)
```

```{r}
#______________________________#
#____    Indicators Score _________ #
#______REGIONAL/INCOME_________#

options(scipen=999)
##LMICS## 
integrated_lmics_score<- scores_nor(integrated2, "Lower middle income")  
integrated_lmics_score_neg<-scores_inv(integrated2, "Lower middle income")
#Join scores
integrated_lmics_score<-left_join(integrated_lmics_score,integrated_lmics_score_neg, by=c('country', "iso3", "region", "income"))
#Filter by income group
integrated_lmics_score <- integrated_lmics_score %>% filter(income=='Lower middle income')

# Save 
write.csv(integrated_lmics_score, paste0(dir_int, "DB_SD_lmics_score.csv"), row.names = FALSE)

##MENA##
integrated_MENA_score<- scores_reg_nor(integrated2, "Middle East & North Africa")  
integrated_MENA_score_neg<-scores_reg_inv(integrated2, "Middle East & North Africa")
#Join scores
integrated_MENA_score<-left_join(integrated_MENA_score,integrated_MENA_score_neg, by=c('country', "iso3", "region", "income"))
#Filter by income group
integrated_MENA_score <- integrated_MENA_score %>% filter(region=='Middle East & North Africa')
# Save 
write.csv(integrated_MENA_score, paste0(dir_int, "DB_SD_MENA_score.csv"), row.names = FALSE)
```





